Vagrant.configure("2") do |config|
  config.vm.box         = "debian/buster64"
  config.vm.box_version = "~> 10.0"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096  # Required for Proxmox to run properly
    v.cpus = 2
  end

  vbox_version = `VBoxManage --version | awk -F'r' '{print $1}'`
  host_port = ENV["HOST_PORT"] || 8006

  config.vm.network "forwarded_port", guest: 8006, host: host_port
  config.vm.provision "shell", path: "src/install-proxmox.sh"
  config.vm.provision :reload
  config.vm.provision "shell", path: "src/install-guest-additions.sh", env: { "VBOX_VERSION": vbox_version }
  config.vm.provision :reload
end
