Vagrant.configure("2") do |config|
  config.vm.box = "proxmox"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096  # Required for Proxmox to run properly
    v.cpus = 2
  end
  host_port = ENV["HOST_PORT"] || 8006
  config.vm.network "forwarded_port", guest: 8006, host: host_port
  # Wait for Proxmox to come up
  proxmox_url = "https://127.0.0.1:#{host_port}"
	config.vm.provision "shell",
    inline: "wait-for-http-status #{proxmox_url} 200 || (echo 'Proxmox failed to come up at #{proxmox_url}, something is broken in the provisioning process'; exit 1)"
end